Gc 12 element section
guvam/guvam pull request #10
Opened 2024-01-31 11:42 UTC by G-Vepkhvadze

1. Created simple component to as filler till we have content for it. tested basic content and seems to fit everything fine.
2. Created section, made entire section responsive.
3.  Created Buttons, currently lack functionality

2024-01-31 11:55 UTC, tarmo-rohelsaar requested changes

2024-01-31 11:55 UTC, tarmo-rohelsaar commented on package.json
> +    "postcss": "^8.4.33",
lets not update package.json without urgent need. It just create headech when changinging branches.

2024-01-31 11:55 UTC, tarmo-rohelsaar commented on packages/website/src/components/sections/Elements.astro
> +      <div class="Element-Showcase-Button">Theme&nbsp<Fragment set:html={SelectorArrow} /></div>
1 insted &nbsp use css gap property
2. can you make them <select> elements and every change you would add class to the .Element-Showcase-Content element . For example SIze select change it would add class size-one, size-two or ... etc.

2024-01-31 11:55 UTC, tarmo-rohelsaar commented on packages/website/src/components/sections/section-components/Element-Component.astro
> +</section>
instead section use div

2024-01-31 11:55 UTC, tarmo-rohelsaar commented on packages/website/src/components/sections/Elements.css
> +    min-inline-size: 89px;
dont specify block sizes.

2024-01-31 12:06 UTC, G-Vepkhvadze commented on package.json
> +    "postcss": "^8.4.33",
I'm not sure how that got there. I didn't change anything

2024-01-31 12:10 UTC, G-Vepkhvadze commented on packages/website/src/components/sections/Elements.astro
> +      <div class="Element-Showcase-Button">Theme&nbsp<Fragment set:html={SelectorArrow} /></div>
I'm not sure I understand number 2.

2024-02-05 06:44 UTC, tarmo-rohelsaar commented
did manual merge already

2024-02-05 06:44 UTC, closed without merging